mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies:
    - { name: '🇻🇳HN1 - Ha Noi', type: vmess, server: hn1.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇻🇳HN2 - Ha Noi', type: vmess, server: vn2.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇻🇳HN3 - Ha Noi', type: vmess, server: vn3.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇻🇳HN4 - Ha Noi', type: vmess, server: vn4.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: dl.ops.kgvn.garenanow.com } }
    - { name: '🇻🇳HN4 - Ha Noi | 443', type: vmess, server: vn4.anhxoai4g.xyz, port: 443, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, tls: true, skip-cert-verify: true, servername: dl.ops.kgvn.garenanow.com, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇻🇳HN5 - Ha Noi', type: vmess, server: vn1.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇻🇳HN5 - Ha Noi | 443', type: vmess, server: vn1.anhxoai4g.xyz, port: 443, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, tls: true, skip-cert-verify: true, servername: dl.ops.kgvn.garenanow.com, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇻🇳HN6 - Lifebox', type: vmess, server: hn6.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: lifebox.vn } }
    - { name: '🇻🇳HCM1 - Ho Chi Minh', type: vmess, server: hcm1.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇻🇳HCM2 - Ho Chi Minh', type: vmess, server: hcm2.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇸🇬SG1 - Singapore', type: vmess, server: sg1.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
    - { name: '🇭🇰HK1 - HongKong', type: vmess, server: hk1.anhxoai4g.xyz, port: 80, uuid: 74bbea51-c970-4648-bb4c-1963410d67e5, alterId: 0, cipher: auto, udp: true, network: ws, ws-path: /, ws-headers: { Host: v.tiktok.com } }
proxy-groups:
    - { name: ANHXOAI4G, type: select, proxies: [自动选择, 故障转移, '🇻🇳HN1 - Ha Noi', '🇻🇳HN2 - Ha Noi', '🇻🇳HN3 - Ha Noi', '🇻🇳HN4 - Ha Noi', '🇻🇳HN4 - Ha Noi | 443', '🇻🇳HN5 - Ha Noi', '🇻🇳HN5 - Ha Noi | 443', '🇻🇳HN6 - Lifebox', '🇻🇳HCM1 - Ho Chi Minh', '🇻🇳HCM2 - Ho Chi Minh', '🇸🇬SG1 - Singapore', '🇭🇰HK1 - HongKong'] }
    - { name: 自动选择, type: url-test, proxies: ['🇻🇳HN1 - Ha Noi', '🇻🇳HN2 - Ha Noi', '🇻🇳HN3 - Ha Noi', '🇻🇳HN4 - Ha Noi', '🇻🇳HN4 - Ha Noi | 443', '🇻🇳HN5 - Ha Noi', '🇻🇳HN5 - Ha Noi | 443', '🇻🇳HN6 - Lifebox', '🇻🇳HCM1 - Ho Chi Minh', '🇻🇳HCM2 - Ho Chi Minh', '🇸🇬SG1 - Singapore', '🇭🇰HK1 - HongKong'], url: 'http://www.gstatic.com/generate_204', interval: 86400 }
    - { name: 故障转移, type: fallback, proxies: ['🇻🇳HN1 - Ha Noi', '🇻🇳HN2 - Ha Noi', '🇻🇳HN3 - Ha Noi', '🇻🇳HN4 - Ha Noi', '🇻🇳HN4 - Ha Noi | 443', '🇻🇳HN5 - Ha Noi', '🇻🇳HN5 - Ha Noi | 443', '🇻🇳HN6 - Lifebox', '🇻🇳HCM1 - Ho Chi Minh', '🇻🇳HCM2 - Ho Chi Minh', '🇸🇬SG1 - Singapore', '🇭🇰HK1 - HongKong'], url: 'http://www.gstatic.com/generate_204', interval: 7200 }
rules:
    - 'IP-CIDR,91.108.4.0/22,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,91.108.8.0/21,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,91.108.16.0/22,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,91.108.56.0/22,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,149.154.160.0/20,ANHXOAI4G,no-resolve'
    - 'IP-CIDR6,2001:67c:4e8::/48,ANHXOAI4G,no-resolve'
    - 'IP-CIDR6,2001:b28:f23d::/48,ANHXOAI4G,no-resolve'
    - 'IP-CIDR6,2001:b28:f23f::/48,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,120.232.181.162/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,120.241.147.226/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,120.253.253.226/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,120.253.255.162/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,120.253.255.34/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,120.253.255.98/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,180.163.150.162/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,180.163.150.34/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,180.163.151.162/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,180.163.151.34/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,203.208.39.0/24,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,203.208.40.0/24,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,203.208.41.0/24,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,203.208.43.0/24,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,203.208.50.0/24,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,220.181.174.162/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,220.181.174.226/32,ANHXOAI4G,no-resolve'
    - 'IP-CIDR,220.181.174.34/32,ANHXOAI4G,no-resolve'
    - 'DOMAIN,injections.adguard.org,DIRECT'
    - 'DOMAIN,local.adguard.org,DIRECT'
    - 'DOMAIN-SUFFIX,local,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'IP-CIDR,224.0.0.0/4,DIRECT'
    - 'IP-CIDR6,fe80::/10,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,ANHXOAI4G'
